### ISSUE TITLE
_version key never gets set correctly if /wp-admin/ lives at another domain

### ISSUE THREAD

**Issue by leedo** [Automattic/batcache#21]
The only place that the `_version` key gets set is in the batcache manager plugin. It uses `get_permalink()` to determine the URL. This is a problem if `/wp-admin/` is accessed through a different domain than the main site. For us it sets the key using `cms.site.com`, but batcache looks it up using `site.com`, so it misses every time. I am not sure how to best fix this, but we have a nasty `str_replace` hacked in for now.

**Comment by vnsavage** [comment]
This means that you probably either don't have advanced-cache.php or WP_CACHE is not set or you're testing in a browser which has been logged in.
