### ISSUE TITLE
Provide an example on how to override default configuration

### ISSUE THREAD

**Issue by andrezrv** [Automattic/batcache#24]
I think an example on how to use a custom configuration would be really helpful for people who don't like reading the code to know how to do that.

I'm doing this by having a file named `batcache-config.php`, which is included in `wp-config.php` this way:

```PHP
if ( file_exists( dirname( __FILE__ ) . '/batcache-config.php' ) ) {
	include( dirname( __FILE__ ) . '/batcache-config.php' );
}
```

And this is the content of my `batcache-config.php`:

```PHP
<?php

// =================
// Batcache settings
// =================

global $batcache;

$batcache = array(
	'max_age'           => 300,
	'remote'            => 0,
	'times'             => 1,
	'seconds'           => 0,
	'group'             => 'batcache',
	'unique'            => array(),
	'headers'           => array(),
	'cache_redirects'   => false,
	'redirect_status'   => false,
	'redirect_location' => false,
	'uncached_headers'  => array( 'transfer-encoding' ),
	'debug'             => true,
	'cache_control'     => true,
	'cancel'            => false,
);
```

Maybe someone could come up with a cleaner way to do this.

I think this is a great plugin, and I hope this helps.

**Comment by mwight4** [comment]
Has anyone ever been able to change the group variable to include the site id? I have a multisite configuration with a long time out, I have code written to dump the cache for single site however batcache is not using site id and I have tried to retrieve it but have not been able to up to this point, I would prefer to not dump the cache for the entire network when I make layout or code fixes

**Comment by vnsavage** [comment]
If you comment out the wp_cache_add_global_groups() code, then the cache will be per-site. Pull requests for default examples are welcome, although the variables seem to be well documented in the advanced-cache.php code.
