### ISSUE TITLE
Page version # can get out of sync with Batcache version # in a nasty way

### ISSUE THREAD

**Issue by ericandrewlewis** [Automattic/batcache#27]
Say I have 180 seconds as the default expiry on Memcached.

Bob creates a blog post at 12:00:00 AM. This increments Batcache's internal cache key that represents the most up-to-date version in the database. Let's call this url_key. The url_key version gets bumped to `1`. url_key will expire in 180 seconds in Memcached, at 12:03:00 AM.

Lisa visits Bob's site at 12:00:30 AM. Batcache doesn't have a copy of this page, so it caches the page. Batcache's internal cache key that represents the version that the cached version of the page is at (let's call this the page cache key) gets set to whatever the url_key is at, so it gets set to `1`. The page cache key gets set to expire at 12:04:00 (the default 180 seconds plus [an extra 30 seconds that Batcache specifies](https://github.com/Automattic/batcache/blob/master/advanced-cache.php#L208)).

At 12:02:00 AM, Bob realizes he made a spelling error, and updates his post. The url_key version gets bumped to `2`, but since the cache key already exists in Memcached, the expiration will still happen at 12:03:00.

No one visits Bob's site until Joey does at 12:03:05. The url_key's expiration time has come, so it gets reset to `0`. However, the page cache key is still at 1, as it doesn't expire until 12:04:00, so Batcache will not recache the page until that time comes, so Bob's copy fix won't be seen until then.

**Comment by vnsavage** [comment]
Thanks for bringing up the issue. Should be fixed in 06d4ffa80130188948f746d44c2721f524ce5f8c.
