### ISSUE TITLE
Batcache not working with WPML

### ISSUE THREAD

**Issue by TangRufus** [Automattic/batcache#32]
Hi!
I have 2 WordPress sites on the same server with Batcache and APC Object Cache Backend plugin installed. Unique WP_APC_KEY_SALT defined on each wordpress site.

All plugins & WordPress core are up-to-date.
Debug option turned on both sites.
No error has been logged in Nginx & php error logs.

When I check the debug message: -
travellersquestion.com ( without WPML ) works perfectly, Batcache message is shown;
tangrufus.com ( with WPML ) shows no trace about Batcache

If WPML is deactivated, Batcache works on tangrufus.com.

Any suggestions to make Batcache works with WPML?

Thanks!

**Comment by vnsavage** [comment]
WPML relies heavily on setting custom cookies, session, query parameters etc and Batcache will not cache a lot of these. You'll need to work with a developer to either add-in configurable exceptions in Batcache or modify the way WPML works.
