### ISSUE TITLE
Deleted post fails to flush cache

### ISSUE THREAD

**Issue by joehoyle** [Automattic/batcache#33]
When a post is deleted, `clean_post_cache` is fired _after_ the post is deleted, this causes the Batcache function `batcache_post` to throw a Notice (as the post doesn't exist) and also fails to clean the cache URL (as the permalink can not be retrieved). My proposed solution would be to hook `batcache_post` into `delete_post` so it can be run _before_ the post is deleted.

**Comment by vnsavage** [comment]
This is fixed now.
