### ISSUE TITLE
Undefined property batcache::$genlock

### ISSUE THREAD

**Issue by Aerendir** [Automattic/batcache#34]
Notice: Undefined property: batcache::$genlock in /base/data/home/apps/s~continuous-wordpress-cms/test-permalink-1.377309360575349926/wordpress/wp-content/advanced-cache.php on line 510

Sometimes it appears reading the posts.

I think that the solution should be simply a declaration of the property at the beginning of the class setting it to "false" or with an empty value.

**Comment by vnsavage** [comment]
This is fixed now.
