### ISSUE TITLE
Undefined property batcache::$query

### ISSUE THREAD

**Issue by Aerendir** [Automattic/batcache#35]
Notice: Undefined property: batcache::$query in /base/data/home/apps/s~continuous-wordpress-cms/test-permalink-1.377309360575349926/wordpress/wp-content/advanced-cache.php on line 388

Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /base/data/home/apps/s~continuous-wordpress-cms/test-permalink-1.377309360575349926/wordpress/wp-includes/plugin.php on line 192

It seems that a simple if statement to assign the property should solve the issue.

**Comment by vnsavage** [comment]
Fixed.
