### ISSUE TITLE
'configure_groups' being called too late?

### ISSUE THREAD

**Issue by mpatek** [Automattic/batcache#37]
Hi, I'm just wondering why you have this line:

    $batcache->configure_groups();

*after* this line:

    $batcache->url_version = (int) wp_cache_get("{$batcache->url_key}_version", $batcache->group);

What if the cache key depends on 'batcache' existing in the set of global groups. Wouldn't it make more sense to switch the two lines?

**Comment by mgburns** [comment]
+1. This is a bug. The `batcache_clear_url()` function defined in `batcache.php` does nothing because of this.

**Comment by Viper007Bond** [comment]
See #46.
