### ISSUE TITLE
serve stale content if necessary

### ISSUE THREAD

**Issue by leedo** [Automattic/batcache#45]
This would probably require a massive refactoring of batcache, but it would be very cool if it could serve stale content in the case that the site is experiencing problems. (e.g. database connection problems)

I believe this would require either adding a grace period to the cache expiration, or doing away with cache expiration entirely. And then storing the real expiration timestamp alongside the cached response. When generating any fresh response you could (hopefully) look for any error status codes, and if there is an error try to use a previously cached version of that page.

**Comment by joshbetz** [comment]
See #39 and #13
