### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by spacedmonkey** [Automattic/batcache#51]
Composer is a popular php dependancy manger. Many of automattic plugins already support it, such as [jetpack](https://github.com/Automattic/jetpack/blob/master/composer.json) and [babble](https://github.com/Automattic/babble/blob/master/composer.json). Supporting it is simple, only requires having a composer.json file in the root of the project and for the repo not using git submodules.  

It is extremely useful if you want to load plugins from github :+1: 

Related #50  #44

**Comment by Viper007Bond** [comment]
#50
