### ISSUE TITLE
Exempt PUT, PURGE, and DELETE requests

### ISSUE THREAD

**Issue by zamoose** [Automattic/batcache#67]
By default, PUT requests aren't exempted from Batcache. This causes... issues with WP-API/JSON, especially when using Basic auth, as there's no cookie to override and cause a bypass. Suggest we bypass for PUT, PURGE, and DELETE requests.

Insert at `advanced-cache.php` line 229:

``` php
// Never batcache on PUT request.
 if ('PUT' === $_SERVER['REQUEST_METHOD'] || 'PURGE' === $_SERVER['REQUEST_METHOD'] || 'DELETE' === $_SERVER['REQUEST_METHOD']) {
    return;
 }
```

I'll put an actual PR in for this too.

Props to @allan23 for working this up.

**Comment by joshbetz** [comment]
We probably shouldn't cache anything that's not `HEAD` or `GET`.
