### ISSUE TITLE
Last-Modified header's value isn't a valid date

### ISSUE THREAD

**Issue by sbgsupport** [Automattic/batcache#7]
Hi,

I'm trying to get around this problem for one my client but unable to find any solution. Here is server header:

curl -I https://saibabaguide.com
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 10 Jun 2012 21:06:02 GMT
Content-Type: text/html
Connection: keep-alive
X-Whom: l2-com-saiba
Vary: Cookie
Last-Modified: Sun, 10 Jun 2012 20:58:34 +0000
Cache-Control: max-age=152, must-revalidate
Front-End-Https: on

The "Last-Modified: Sun, 10 Jun 2012 20:58:34 +0000" should be "Last-Modified: Sun, 10 Jun 2012 20:58:34 GMT". Is there any setting to change this? In my php.ini, i got the following line:
date.timezone=America/Chicago

How do I change +0000 to GMT. 

Thanks!
!

**Comment by vnsavage** [comment]
This issue has been fixed.
